---
title: "ESM244lab1"
author: "MaddieFrick"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
library(tidyverse)
library(here) #for nice paths to read in data in a project
library(sf) #spacial data wrangling
library(tmap) #to make an interactive map
```

### Read in SF trees data 

```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv")) #gives a robust file path
```

### Basic wrangling reminders

Refresh some skills for data wrangling and summary statistics using functions in 'diplyr' package

Find the top five highest observations of trees by legal_Status, do some wrangling, make a graph

```{r}

top_five_status <- sf_trees %>% 
  count(legal_status) %>%  #count recognizes finds counts of observations based on one or more variables :groups (replacing group by), finds counts (replaces n), puts it in a table (replaces summarize)
  drop_na(legal_status) %>% #drops all of the NA row where NA is in the legal status row
  rename(tree_count = n) %>%  #new name left old name right
  relocate(tree_count) %>% #this brings tree count to the first column position
  slice_max(tree_count, n = 5) #allows to identify by highest value in a variable


  

```
